import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { GetServerSideProps, GetStaticProps, NextPage } from "next";
import { ReadAllDataType } from "@/utils/types";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage<ReadAllDataType> = ({ allItems }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <div className="max-w-screen-xl px-4 py-8 mx-auto sm:px-6 sm:py-12 lg:px-8">
          <header className="flex justify-between ">
            <div className="grow">
              <h2 className="text-xl font-bold text-gray-900 sm:text-3xl">
                Product Collection
              </h2>

              <p className="max-w-xl mt-4 text-gray-500">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque
                praesentium cumque iure dicta incidunt est ipsam, officia dolor
                fugit natus?
              </p>
            </div>
            <div className="">
              <p>アイテム作成</p>
            </div>
          </header>

          <ul className="grid gap-4 mt-8 sm:grid-cols-2 lg:grid-cols-4">
            {allItems.map((item) => (
              <li key={item._id} className={item._id}>
                <Link href={`item/${item._id}`} className="block overflow-hidden group">
                  <Image
                    src={item.image}
                    alt={item.title}
                    width={750}
                    height={500}
                    className="h-[350px] w-full object-cover transition duration-500 group-hover:scale-105 sm:h-[450px]"
                  />

                  <div className="relative pt-3 bg-white">
                    <h3 className="text-xs text-gray-700 group-hover:underline group-hover:underline-offset-4">
                      {item.title}
                    </h3>

                    <p className="mt-2">
                      <span className="sr-only"> Regular Price </span>

                      <span className="tracking-wider text-gray-900">
                        {" "}
                        ￥{item.price}{" "}
                      </span>
                    </p>
                  </div>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </section>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<
  ReadAllDataType
> = async () => {
  const res = await fetch("http://localhost:3000/api/item/readAll");

  const allItems = await res.json();
  return {
    props: allItems,
  };
};

export default Home;
